version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Dutchskull.Aspire.AppHost.Unity3D"
    target-branch: "develop"
    groups:
      allDependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
