version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Dutchskull.Aspire.AppHost.Unity3D"
    target-branch: "develop"
    groups:
      allDependencies:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FluentAssertions"
        versions: [ ">=8.0.0" ]
      - dependency-name: "Aspire*"
        versions: [ ">=9.0.0" ]
